-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- Add any additional autocmds here

------------------------------------------------------- Session Manager
-- local config_group = vim.api.nvim_create_augroup("MyConfigGroup", {}) -- A global group for all your config autocommands
--
-- vim.api.nvim_create_autocmd({ "User" }, {
--   pattern = "SessionLoadPost",
--   group = config_group,
--   callback = function()
--     vim.cmd("NeoTreeShow")
--   end,
-- })

------------------------------------------------------- Formatter
-- vim.api.nvim_create_autocmd("BufWritePre", {
--   pattern = "*",
--   callback = function(args)
--     require("conform").format({ bufnr = args.buf })
--   end,
-- })
